#!/bin/sh

NAME=localdev

multipass delete --all --purge -vv
multipass launch -m 4G -d 10G -c 2 -n $NAME --cloud-init cloud-init.yaml -vv
multipass exec $NAME -- sudo cloud-init status --wait
multipass exec $NAME -- sudo usermod -a -G microk8s ubuntu
multipass exec $NAME -- sudo chown -f -R ubuntu ~/.kube
multipass exec $NAME -- sudo microk8s config view > ~/.kube/config
multipass list
kubectl kustomize --enable-helm . | kubectl apply -f -
sleep 180
# kubectl -n argocd wait --for=condition=complete pods -l
# while [[ $(kubectl get pods -l app=hello -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do echo "waiting for pod" && sleep 1; done
sh grant_access