dex:
  enabled: true
server:
  # extraArgs:
  # - --insecure
  service:
    type: LoadBalancer
  configEnabled: true
  config:
    # kustomize.buildOptions: --enable-alpha-plugins --enable-helm"
    kustomize.buildOptions: --enable-helm
    repositories: |
      - type: helm
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
      - type: git
        name: app-of-apps
        url: https://github.com/bdx0/app-of-apps.git
  # additionalApplications:
  # - name: root-app
  #   namespace: argocd
  #   additionalLabels: {}
  #   additionalAnnotations:
  #     "helm.sh/resource-policy": keep # <-- add this
  #   finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  #   destination:
  #     server: https://kubernetes.default.svc
  #     namespace: default
  #   project: default
  #   source:
  #     path: apps/
  #     repoURL: https://github.com/bdx0/app-of-apps.git
  #     targetRevision: HEAD
  #     # kustomize: {}
  #     # enableHelm: true
  #   syncPolicy:
  #     automated:
  #       prune: true
  #       selfHeal: true
  #       allowEmpty: true
  #     syncOptions:
  #     - PruneLast=true
  #     - CreateNamespace=true
  #     - Validate=true
  #     - PrunePropagationPolicy=foreground
  #     - PruneLast=true
  #     - ApplyOutOfSync=true
