apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
- namespace.yaml
# - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.7.1/deploy/static/provider/baremetal/deploy.yaml
# - https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
- ingress.yaml
# - argocd-cm.yaml

helmCharts:
  - name: argo-cd
    includeCRDs: true
    releaseName: argo-cd
    # version: 4.2.2
    repo: https://argoproj.github.io/argo-helm
    valuesFile: argocd-values.yaml
  - name: argocd-apps
    includeCRDs: true
    releaseName: argocd-apps
    # version: 4.2.2
    repo: https://argoproj.github.io/argo-helm
    valuesFile: argocd-apps-values.yaml