# argo-cd:
dex:
  enabled: true
server:
  # extraArgs:
    # - --insecure
  service:
      type: NodePort
  configEnabled: true
  config:
    repositories: |
      - type: helm
        name: argo-cd
        url: https://argoproj.github.io/argo-helm
    additionalApplications:
    - name: root-app
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      project: default
      source:
        path: apps/
        repoURL: https://github.com/bdx0/app-of-apps.git
        targetRevision: HEAD
        kustomize:
          enableHelm: true
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
        - PruneLast=true
        - CreateNamespace=true
        - Validate=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        - ApplyOutOfSync=true