apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  project: default
  sources:
    # - repoURL: https://kubernetes.github.io/dashboard/
    #   targetRevision: 7.0.3
    #   chart: kubernetes-dashboard
    #   helm:
    #     ignoreMissingValueFiles: true
    #     valueFiles:
    #       - $values/apps/values/kubernetes-dashboard-values.yaml
    - repoURL: https://github.com/bdx0/k8s_kuz_wp.git
      targetRevision: HEAD
      path: manifests
      kustomize:
        enableHelm: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# helmCharts:
#   - name: kubernetes-dashboard
#     includeCRDs: true
#     releaseName: kubernetes-dashboard
#     # version: 4.2.2
#     repo: https://kubernetes.github.io/dashboard/
#     valuesFile: kubernetes-dashboard-values.yaml
