apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: aoa

resources:
  - namespace.yaml
  # - app-root.yaml
  - app-kubernetes-dashboard.yaml
  - app-argo-cd.yaml
  - app-prometheus.yaml
  # - ingress-k8s-dashboard.yaml
  # - ingress-argo-cd.yaml
  - dashboard-admin.yaml
  - app-wordpress.yaml
# helmCharts:
#   - name: kubernetes-dashboard
#     includeCRDs: true
#     releaseName: kubernetes-dashboard
#     # version: 4.2.2
#     repo: https://kubernetes.github.io/dashboard/
#     valuesFile: kubernetes-dashboard-values.yaml
