apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace: aoa

resources:
  - namespace.yaml
  # - app-root.yaml
  - app-argo-cd.yaml
  - app-prometheus.yaml
  - ingress-k8s-dashboard.yaml
  - ingress-argo-cd.yaml
